import image1 from "../assets/images/project_1.png";
import image2 from "../assets/images/project_2.png";
import image3 from "../assets/images/project_3.png";
import image4 from "../assets/images/project_4.png";
import image5 from "../assets/images/project_2.png";
import image6 from "../assets/images/project_3.png";
import image7 from "../assets/images/press_2.png";

export const data = [
  {
    id: 1,
    image: image1,
    title: "Funding",
    curated: false,
    trending: true,
    treasuryFunded: false,
    rewards: true,
    subTitle: "The world in shambles",
    content:
      "Step into a post apocalyptic world where only Bitcoin can save the people",
    subContent: "Bitcoin Metaverse",
    time: "24 days left",
    barRate: "23000",
    barTitle: "STX raised",
    barPercent: "23%",
  },
  {
    id: 2,
    image: image2,
    title: "Funding",
    curated: true,
    trending: true,
    treasuryFunded: true,
    rewards: true,
    subTitle: "Bwallet: Software wallet for Bitcoin",
    content:
      "Bringing you an easy to use Bitcoin wallet with Ordinals, Stamps and BRC-20 integrations",
    subContent: "wallets",
    time: "24 days left",
    barRate: "23000",
    barTitle: "BTC raised",
    barPercent: "23%",
  },
  {
    id: 3,
    image: image3,
    title: "Funding",
    curated: true,
    trending: true,
    treasuryFunded: false,
    rewards: true,
    subTitle: "Project eduBTC",
    content:
      "A virtual educational program focused on Bitcoin education for the masses. We go into  every aspect of Bitcoin integration",
    subContent: "bitcoin education",
    time: "24 days left",
    barRate: "23000",
    barTitle: "STX raised",
    barPercent: "23%",
  },
  {
    id: 4,
    image: image4,
    title: "Funding",
    curated: false,
    trending: false,
    treasuryFunded: true,
    rewards: true,
    subTitle: "MinePRO: A self mining suite for Bitcoin miners",
    content:
      "CYBERFROG: HEARTSICK DELUXE Edition! Let's RACE with CYBERFROG! MINI-CARS!",
    subContent: "mining",
    time: "24 days left",
    barRate: "23000",
    barTitle: "STX raised",
    barPercent: "23%",
  },
  {
    id: 5,
    image: image5,
    title: "Funding",
    subTitle: "Bwallet: Software wallet for Bitcoin",
    curated: true,
    trending: false,
    treasuryFunded: true,
    rewards: false,
    content:
      "Bringing you an easy to use Bitcoin wallet with Ordinals, Stamps and BRC-20 integrations",
    subContent: "wallets",
    time: "24 days left",
    barRate: "23000",
    barTitle: "BTC raised",
    barPercent: "23%",
  },
  {
    id: 6,
    image: image6,
    title: "Funding",
    checked2: "Treasury Funded",
    subTitle: "HoogaBTC: An experiential game built on-chain",
    curated: true,
    trending: false,
    treasuryFunded: false,
    rewards: false,
    content:
      "Bringing you a world of adventure and mystery. Dive into an experience unlike any and for the first time ITS ON CHAIN",
    subContent: "bitcoin games",
    time: "24 days left",
    barRate: "23000",
    barTitle: "STX raised",
    barPercent: "23%",
  },
  {
    id: 7,
    image: image7,
    title: "Funding",
    subTitle: "The Ordinal Punks: An Ordinal collection on Bitcoin",
    curated: false,
    trending: true,
    treasuryFunded: true,
    rewards: false,
    content:
      "A collection of 10,000 punks living on Bitcoin with different traits",
    subContent: "ordinals",
    time: "24 days left",
    barRate: "23000",
    barTitle: "BTC raised",
    barPercent: "23%",
  },
];
